[package]
name = "musig"
version = "0.1.0"
authors = ["elsirion <elsirion@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bincode = "1.3.1"
secp256kfun = { version = "0.4.1", features = [ "serde" ] }
serde = { version = "1.0.118", features = [ "derive" ] }
sha3 = "0.9.1"
rand = "0.6.5"