name: fedimint-dev
root: .
socket_name: fedimint-dev
pre_window:
  - source .tmpenv
  - source scripts/lib.sh
  - source scripts/aliases.sh
tmux_detached: false
windows:
  - main:
      panes:
        - user:
            - source scripts/tmux-user-shell.sh
  - federation:
      panes:
        - federation:
          - tail -n +0 -F $FM_LOGS_DIR/fedimint-*.log
  - lightning:
      layout: tiled
      panes:
        - cln:
          - tail -n +0 -F $FM_LOGS_DIR/lightningd.log
        - lnd:
          - tail -n +0 -F $FM_LOGS_DIR/lnd.log
        - cln-gw:
          - tail -n +0 -F $FM_LOGS_DIR/gatewayd-cln.log
        - lnd-gw:
          - tail -n +0 -F $FM_LOGS_DIR/gatewayd-lnd.log
  - bitcoin:
      panes:
        - bitcoind:
          - tail -n +0 -F $FM_LOGS_DIR/bitcoind.log
