name: fedimint-dev
root: .
socket_name: fedimint-dev
pre_window:
  - source .tmpenv
  - alias lightning-cli="\$FM_LIGHTNING_CLI"
  - alias lncli="\$FM_LNCLI"
  - alias bitcoin-cli="\$FM_BTC_CLIENT"
  - alias fedimint-cli="\$FM_MINT_CLIENT"
  - alias gateway-cln="\$FM_GWCLI_CLN"
  - alias gateway-lnd="\$FM_GWCLI_LND"
  - alias mint_rpc_client="\$FM_MINT_RPC_CLIENT"
  - alias dbtool="\$FM_DB_TOOL"
  - alias restart="./scripts/restart-tmux.sh"
  - source scripts/lib.sh
tmux_detached: false
windows:
  - main:
      panes:
        - user:
            - source scripts/tmux-user-shell.sh
  - federation:
      panes:
        - federation:
          - run_dkg
          - start_federation &
  - lightning:
      layout: tiled
      panes:
        - cln:
          - start_lightningd &
          - fg
        - lnd:
          - start_lnd &
          - fg
        - cln-gw:
          - start_cln_gateway &
          - fg
        - lnd-gw:
          - start_lnd_gateway &
          - fg
  - bitcoin:
      panes:
        - bitcoind:
          - start_bitcoind
          - fg
