[package]
name = "minimint"
version = "0.1.0"
authors = ["elsirion <elsirion@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bincode = "1.3.1"
blindsign = { path = "../blindsign" } # { git = "***REMOVED***" }
curve25519-dalek = "3.0.2"
futures = "0.3.9"
hbbft = "0.1.1"
rand = "0.6.5"
serde = "1.0.118"
sha3 = "0.9.1"
structopt = "0.3.21"
tokio = { version = "1.0.1", features = ["full"] }
tokio-stream = "0.1.1"
tokio-util = { version = "0.6.0", features = [ "compat" ] }
tracing ="0.1.22"
tracing-subscriber = "0.2.15"