[package]
name = "minimint"
version = "0.1.0"
authors = ["elsirion <elsirion@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.9"
hbbft = "0.1.1"
structopt = "0.3.21"
tokio = { version = "1.0.1", features = ["full"] }
tokio-stream = "0.1.1"