[workspace]

members = [
    "crypto/tbs",
    "ln-gateway",
    "minimint",
    "minimint-core",
    "minimint-derive",
    "minimint-api",
    "client/cli",
    "client/client-lib",
    "modules/minimint-mint",
    "modules/minimint-ln",
    "modules/minimint-wallet",
    "integrationtests",
]

[patch.crates-io]
bitcoin_hashes = { version = "0.10.0", git = 'https://github.com/fedimint/bitcoin_hashes', branch = 'minimint' }
secp256k1-zkp = { git = "https://github.com/sanket1729/rust-secp256k1-zkp/", branch = "pr29" }