[workspace]

members = [
    "crypto/musig",
    "crypto/tbs",
    "ln-gateway",
    "minimint",
    "minimint-derive",
    "minimint-api",
    "mint-client",
    "modules/minimint-mint",
    "modules/minimint-wallet",
]

[patch.crates-io]
bitcoin_hashes = { git = 'https://github.com/elsirion/bitcoin_hashes', branch = 'minimint' }