[package]
name = "fedimint"
version = "0.1.0"
authors = ["elsirion <elsirion@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
counter = "0.5.2"
mint-api = { path = "../mint-api" }
tbs = { path = "../crypto/tbs" }
tracing ="0.1.22"
