[package]
name = "fedimint-dummy-client"
version = "0.1.0"
authors = ["The Fedimint Developers"]
edition = "2021"
description = "fedimint-dummy is a dummy example fedimint module."
license = "MIT"

[lib]
name = "fedimint_dummy_client"
path = "src/lib.rs"

[dependencies]
fedimint-dummy-common ={ path = "../fedimint-dummy-common" }
