[package]
name = "fediwallet"
version = "0.1.0"
authors = ["elsirion <elsirion@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bdk = "0.4.0"
bitcoin = { version = "0.26.0", features = [ "rand" ] }
rand = "0.6.0"
serde = { version = "1.0.118", features = [ "derive" ] }
thiserror = "1.0.23"
tokio = { version = "1.0.1", features = ["full"] }
tracing ="0.1.22"
