[package]
name = "minimint"
version = "0.1.0"
authors = ["elsirion <elsirion@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bincode = "1.3.1"
config = { path = "../config", features = [ "server" ] }
fedimint = { path = "../fedimint" }
futures = "0.3.9"
hbbft = "0.1.1"
hex = "0.4.2"
mint-api = { path = "../mint-api" }
musig = { path = "../crypto/musig" }
rand = "0.6.5"
serde = { version = "1.0.118", features = [ "derive" ] }
sha3 = "0.9.1"
structopt = "0.3.21"
tbs = { path = "../crypto/tbs" }
thiserror = "1.0.23"
tide = "0.16.0"
tokio = { version = "1.0.1", features = ["full"] }
tokio-util = { version = "0.6.0", features = [ "compat" ] }
tracing ="0.1.22"
tracing-subscriber = "0.2.15"