[profile.default]
# no matter the profile, we want to kill tests that hanged on something
slow-timeout = { period = "60s", terminate-after = 8 }

[profile.ci]
fail-fast = true
failure-output = "immediate"
slow-timeout = { period = "60s", terminate-after = 4 }
