[package]
name = "mint-api"
version = "0.1.0"
authors = ["elsirion <elsirion@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bincode = "1.3.1"
bitcoin_hashes = { version = "0.9.4", features = ["serde"] }
musig = { path = "../crypto/musig"}
serde = { version = "1.0.118", features = [ "derive" ] }
sha3 = "0.9.1"
tbs = { path = "../crypto/tbs"}
