[package]
name = "mint-api"
version = "0.1.0"
authors = ["elsirion <elsirion@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bincode = "1.3.1"
bitcoin = { version = "0.26.0", features = [ "rand", "serde" ] }
bitcoin_hashes = { version = "0.9.4", features = ["serde"] }
hex = "0.4.3"
miniscript = "5.1.0"
musig = { path = "../crypto/musig"}
secp256k1 = { version = "0.20.1", features = [ "serde" ] }
serde = { version = "1.0.118", features = [ "derive" ] }
sha3 = "0.9.1"
tbs = { path = "../crypto/tbs"}
thiserror = "1.0.23"
validator = { version = "0.13", features = ["derive"] }
