[package]
name = "fedimint-testing"
version = "0.1.0"
authors = ["The Fedimint Developers"]
edition = "2021"
description = "mint-client provides a library for sending transactions to the federation."
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "fedimint_testing"
path = "src/lib.rs"


[dependencies]
async-trait = "*"
bitcoin = "0.29.2"
fedimint-api  = { path = "../fedimint-api" }
fedimint-bitcoind = { path = "../fedimint-bitcoind" }
secp256k1-zkp = { version = "0.7.0", features = [ "global-context", "bitcoin_hashes" ] }
serde_json = "*"
rand = "0.8"
