[package]
name = "mint-client"
version = "0.1.0"
authors = ["elsirion <elsirion@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.13.0"
bincode = "1.3.1"
bitcoin = { version = "0.26.0" }
bitcoin_hashes = "0.9.4"
config = { path = "../config", features = [ "client" ] }
database = { path = "../database" }
futures = "0.3.9"
hex = "0.4.3"
lightning-invoice = "0.5.0"
miniscript = "5.1.0"
mint-api = { path = "../mint-api" }
musig = { path = "../crypto/musig" }
rand = "0.6.5"
reqwest = { version = "0.11.0", features = [ "json" ], default-features = false }
secp256k1 = { version = "0.20.1", features = [ "serde", "bitcoin_hashes" ] }
serde = { version = "1.0.118", features = [ "derive" ] }
sha3 = "0.9.1"
sled = "0.34.6"
structopt = "0.3.21"
tbs = { path = "../crypto/tbs" }
thiserror = "1.0.23"
tokio = { version = "1.0.1", features = ["full"] }
tracing ="0.1.22"
tracing-subscriber = "0.2.15"
