[package]
name = "mint-client"
version = "0.1.0"
authors = ["elsirion <elsirion@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mint-api = { path = "../mint-api" }
musig = { path = "../crypto/musig" }
rand = "0.6.5"
tbs = { path = "../crypto/tbs" }
thiserror = "1.0.23"

[dev-dependencies]
bincode = "1.3.1"
config = { path = "../config", features = [ "client" ] }
reqwest = { version = "0.11.0", features = [ "rustls-tls", "json" ], default-features = false }
serde_json = "1.0.61"
sha3 = "0.9.1"
structopt = "0.3.21"
tokio = { version = "1.0.1", features = ["full"] }
tracing ="0.1.22"
tracing-subscriber = "0.2.15"
