on:
  push:
    branches:
      - master
  pull_request:

name: CI - basic

jobs:
  build:
    name: Build ${{ matrix.build }}

    strategy:
      matrix:
        build:
          - macos
        include:
          - build: macos
            runs-on: macos-latest
            use-cross: false
            # TODO: Too slow; see https://github.com/actions/runner-images/issues/1336
            build-in-pr: false
            extra-cmd: brew install protobuf

    runs-on: ${{ matrix.runs-on }}
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v3
        # Note: making the whole job conditional w.r.t matrix, instead of every step
        # is not supported and workarounds are very gnarly
        if: github.ref == 'refs/heads/master' || matrix.build-in-pr

      - name: Extra command
        if: (github.ref == 'refs/heads/master' || matrix.build-in-pr) && matrix.extra-cmd != ''
        run: |
          ${{ matrix.extra-cmd }}

      - uses: cachix/install-nix-action@v20
        if: github.ref == 'refs/heads/master' || matrix.build-in-pr
        with:
          nix_path: nixpkgs=channel:nixos-22.05
      - uses: cachix/cachix-action@v12
        if: github.ref == 'refs/heads/master' || matrix.build-in-pr
        with:
          name: fedimint
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
        continue-on-error: true

      - name: Build workspace
        if: github.ref == 'refs/heads/master' || matrix.build-in-pr
        run: nix build -L .#debug.workspaceBuild

      - name: Clippy workspace
        if: github.ref == 'refs/heads/master' || matrix.build-in-pr
        run: nix build -L .#debug.workspaceClippy
