on: [push, pull_request]

name: CI

jobs:
  build_and_unit_test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2021-05-09
          default: true
      - uses: actions-rs/cargo@v1
        with:
          command: version
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --all-features --all-targets --workspace
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-features --workspace
      - uses: actions-rs/cargo@v1
        with:
          command: doc
          args: --all-features
  build_and_integration_test:
    name: Integration Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2021-05-09
          default: true
      - run: scripts/integrationtest.sh