on:
  push:
    branches:
      - master
  pull_request:

name: CI

jobs:
  build_wasm:
    name: Build (wasm32)
    runs-on: buildjet-8vcpu-ubuntu-2004
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          target: wasm32-unknown-unknown
          profile: minimal
      - uses: Swatinem/rust-cache@v1
      - name: Build modules/mint-client
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --target wasm32-unknown-unknown --package mint-client
